/*
 * File: pa4Strings.h
 * Description: Header file containing strings that are displayed to the user.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef _PA4_STRINGS_H /* Header Guard. */
#define _PA4_STRINGS_H

#define STR_USAGE_SHORT ""\
  "%s [-h] [-x | -o | -c | -s] [-l | -b] [-r range] [-u outfile] INFILE\n\n"

#define STR_USAGE_LONG  STR_USAGE_SHORT \
  "Options:\n" \
  " -h/--help:\t\tPrint this help message.\n" \
  " -x/--hex:\t\tOutput bytes as hexadecimal.\n" \
  " -o/--octal:\t\tOutput bytes as octal.\n" \
  " -c/--ascii:\t\tOutput bytes as ASCII.\n" \
  " -s/--string:\t\tStrings mode.\n" \
  " -b/--big-endian:\tConvert data to big-endian.\n" \
  " -l/--little-endian:\tConvert data to little-endian.\n" \
  " -r/--range:\t\tOnly print range from file.\n" \
  "\t\t\tMust be in the form start:end, end > start.\n" \
  " -u/--undump:\t\tConvert hexdump into binary. " \
  "Writes out to file.\n\n"

#define STR_STRING_OUT  "%s\n"
#define STR_OCTAL_FMT   "%03o"
#define STR_ASCII_FMT   "%2c"
#define STR_HEX_FMT     "%02x"
#define STR_SPACE       " "
#define STR_OFFSET_OCT  "%07lo: "
#define STR_OFFSET_HEX  "%07lx: "
#define STR_SCANF       "%2hhx%2hhx"
#define STR_SCANF_OFF   "%*x:"

/* ===== Error Strings. ===== */
#define ERR_NUM_ARGS    "Error: Incorrect number of positional arguments.\n"
#define ERR_OUT_FLAGS   "Error: Only one of -x, -c, -o, -s may be specified.\n"
#define ERR_END_FLAGS   "Error: Only one of -b or -l may be specified.\n"
#define ERR_RANGE_FMT   "Error: Incorrect format for range.\n"
#define ERR_NOT_INT     "Error: %s could not be converted to an integer.\n"
#define ERR_RANGE_INV   "Error: Invalid range. Start and end must be > 0, " \
                        "end > start\n"

#endif /* pa4Strings.h */
