/*
 * File: pa4Strings.h
 * Description: Header file containing strings that are displayed to the user.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA1_STRINGS_H    /* Macro guard */
#define PA1_STRINGS_H


/* Usage string */
#define STR_USAGE "\nUsage: %s width height border_char diamond_char\n"\
  "    width        (must be odd within the range of [%d - %d])\n"\
  "    height       (must be odd within the range of [%d - %d])\n"\
  "                 (must be less than width)\n"\
  "    border_char  (must be single char within the ASCII range [%d - %d])\n"\
  "                 (must be different than diamond_char)\n"\
  "    diamond_char (must be single char within the ASCII range [%d - %d])\n"\
  "                 (must be different than border_char)\n\n"


/* You will need to use these within some of the error messages */
#define STR_WIDTH "width"
#define STR_HEIGHT "height"
#define STR_BORDER_CHAR "border_char"
#define STR_DIAMOND_CHAR "diamond_char"


/* Error strings */
#define STR_ERR_NUM_RANGE "\n\t %s(%ld) must be within the range of [%d - %d]\n"

#define STR_ERR_ODD "\n\t %s(%ld) must be an odd number\n"

#define STR_ERR_CONVERTING "\n\t converting %s(%s) in base(%d) to long"

#define STR_ERR_SINGLE_CHAR "\n\t %s(%s) must be a single character\n"

#define STR_ERR_NOT_INT "\n\t %s(%s) must be an integer\n"

#define STR_ERR_ASCII_RANGE "\n\t %s(%c) must be within the ASCII range"\
  " [%d - %d]\n"

#define STR_ERR_HEIGHT_LESS_THAN_WIDTH "\n\t height(%ld) must be less than"\
  " width(%ld)\n"

#define STR_ERR_BORDER_DIAMOND_DIFF "\n\t border_char(%c) and diamond_char(%c)"\
  " must be different\n"


#endif /* PA1_STRINGS_H */
