/*
 * File: pa3Globals.c
 * Description: Global variables for pa3.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

/*
 * C standard library headers
 */
#include <stddef.h> // offsetof

/*
 * Assignment header(s)
 */
#include "pa3.h"

size_t wordOffset = offsetof( struct Anagram, word );
size_t keyOffset = offsetof( struct Anagram, key );
