/*
 * File: pa3Strings.h
 * Description: Header file containing strings that are displayed to the user.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA3_STRINGS_H    /* Macro Guard */
#define PA3_STRINGS_H

/* Usage strings for Spawn Anagrams */
#define STR_SPAWN_USAGE_LONG "\n"\
  "Usage: %s [-d dictionaryFile] [-a anagramFile] [-h]\n"\
  "Reads in a dictionary file and outputs an anagram file.\n"\
  "  -d <dictionaryFile>   Name of the dictionary file to use;\n"\
  "                        Each word in file is separated by a newline.\n"\
  "                        Defaults to /usr/share/dict/words if unspecified.\n"\
  "  -a <anagramFile>      The name of the anagram file to output;\n"\
  "                        The extention \".ao\" is automatically appended.\n"\
  "                        Defaults to \"anagramPrey.ao\" if unspecified.\n"\
  "  -h                    Prints the long usage.\n"\
  "\n"

#define STR_SPAWN_USAGE_SHORT "\n"\
  "Usage: %s [-d dictionaryFile] [-a anagramFile]\n"\
  "Try '%s -h' for more information.\n\n"


/* Usage string for Hunt Anagrams */
#define STR_HUNT_USAGE "\n"\
  "Usage: %s anagramFile\n"\
  "    anagramFile    (file extension must end in \".ao\")\n"\
  "                   (file size must be divisible by sizeof(Anagram))\n\n"


/* Strings for printing Spawn Anagrams statistics */
#define STR_SPAWN_ARRAY "\n\tSpawned anagram array with %d anagrams.\n"
#define STR_SPAWN_FILE "\n\tSpawned anagram file (%s.ao) with %d anagrams.\n\n"

/* Strings for printing Hunt Anagrams statistics */
#define STR_HUNT_FILE "\n\tReading anagram file (%s) with %d anagrams.\n"
#define STR_HUNT_ARRAY "\n\tLoaded anagram array with %d anagrams.\n\n"

/* Interactive prompt strings for Hunt Anagrams */
#define STR_USER_PROMPT "\nEnter a word to hunt for anagrams [^D to exit]: "
#define STR_NO_ANAGRAMS "No anagrams found.\n"
#define STR_FOUND_ANAGRAMS "Anagram(s) are: "
#define STR_SPACE_CHAR " "

/* Error strings for spawning anagrams */
#define STR_ERR_DICT_FILE_PERMISSION "\n"\
  "\tError opening dictionary file (%s); permission denied.\n"
#define STR_ERR_DICT_FILE_INVALID "\n"\
  "\tError opening dictionary file (%s); invalid file.\n"
#define STR_ERR_CREATE_ANAGRAM_FILE "\n"\
  "\tError creating anagram file (%s).\n"

/* Error strings for hunting anagrams */
#define STR_ERR_ANAGRAM_FILE_EXT "\n"\
  "\tError opening anagram file (%s); must have %s extension.\n\n"
#define STR_ERR_ANAGRAM_FILE_PERMISSION "\n"\
  "\tError opening anagram file (%s); permission denied.\n"
#define STR_ERR_ANAGRAM_FILE_INVALID "\n"\
  "\tError opening anagram file (%s); invalid file.\n"
#define STR_ERR_ANAGRAM_FILE_CORRUPT "\n"\
  "\tError reading anagram file (%s); corrupt file (invalid file length).\n"

/* General error strings */
#define STR_ERR_EXTRA_ARGS "\n\tExtra operand '%s'.\n"
#define STR_ERR_MEM_EXCEEDED "\n\tMemory limit exceeded.\n"

#endif /* PA3_STRINGS_H */
